# Generated by Django 5.2 on 2025-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nivel_dificuldade',
        ),
        migrations.AddField(
            model_name='servico',
            name='niveis_dificuldade',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Iniciante', max_length=30),
            preserve_default=False,
        ),
    ]
