# Generated by Django 5.2 on 2025-05-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='permissoes',
        ),
    ]
