# Generated by Django 5.2 on 2025-05-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_contareceber_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='horarios_trabalho',
            field=models.TextField(blank=True),
        ),
    ]
