# Generated by Django 5.2 on 2025-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_servico_nivel_dificuldade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_horaria', models.FloatField()),
                ('horarios_trabalho', models.JSONField(default=list)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha_hash', models.CharField(max_length=128)),
                ('permissoes', models.JSONField(default=list)),
                ('is_admin', models.BooleanField(default=False)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
