# Generated by Django 5.2 on 2025-05-13 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_funcionario_horarios_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ultimo_acesso',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
