# Generated by Django 5.2 on 2025-05-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_funcionario_salario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='senha_hash',
            new_name='senha',
        ),
    ]
