# Generated by Django 5.2 on 2025-05-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_senha_hash_funcionario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('cancelada', models.BooleanField(default=False)),
                ('servicos', models.ManyToManyField(to='studio.servico')),
            ],
        ),
        migrations.CreateModel(
            name='AulaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='studio.aula')),
            ],
        ),
    ]
