# Generated by Django 5.2 on 2025-06-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_aula_aulaaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='id',
        ),
        migrations.AlterField(
            model_name='plano',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_vigencia',
            field=models.CharField(choices=[('M', 'Mensal'), ('T', 'Trimestral'), ('S', 'Semestral')], max_length=1),
        ),
    ]
