# Generated by Django 5.2 on 2025-06-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_horariodisponivel_agendamento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariodisponivel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='servico',
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='HorarioDisponivel',
        ),
    ]
