# Generated by Django 5.2 on 2025-07-09 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_horariodisponivel_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.funcionario'),
        ),
        migrations.AddField(
            model_name='aulaaluno',
            name='evolucao_na_aula',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default='Motivo não informado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='evolucao',
            field=models.TextField(blank=True, default='Evolução não informada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, default='Descrição não informada'),
            preserve_default=False,
        ),
    ]
