# Generated by Django 5.2 on 2025-07-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_aula_funcionario_aulaaluno_evolucao_na_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='funcionario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='studio.funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aulaaluno',
            name='evolucao_na_aula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
