# Generated by Django 5.2 on 2025-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_aula_funcionario_aulaaluno_evolucao_na_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
