# Generated by Django 5.2 on 2025-07-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_alter_agendamento_motivo_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aulaaluno',
            name='evolucao_na_aula',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
