# Generated by Django 5.2 on 2025-07-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_alter_agendamento_motivo_cancelamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='evolucao',
        ),
    ]
